# AI Models Configuration
# Following Linux config philosophy: Simple, readable, version-controlled

models:
  # Production models - paid
  production:
    reasoning: "claude-3-5-sonnet-20241022"
    coding: "qwen/qwen-2.5-coder-32b-instruct"
    multimodal: "gpt-4o"
    fast: "claude-3-haiku-20240307"
    
  # Free tier models
  free:
    general: "qwen/qwen-2.5-coder-32b-instruct"
    coding: "qwen/qwen-2.5-coder-32b-instruct" 
    chinese: "glm-4-plus"
    backup: "microsoft/wizardlm-2-8x22b"

# Model routing rules
routing:
  keywords:
    code: ["python", "javascript", "code", "programming", "function", "class"]
    reasoning: ["analyze", "think", "reason", "complex", "logic"] 
    medical: ["症状", "治疗", "药物", "疾病", "健康", "医疗"]
    multimodal: ["image", "photo", "picture", "图片", "图像"]
  
  rules:
    - if: "any(keyword in query.lower() for keyword in keywords.code)"
      then: "models.production.coding if paid else models.free.coding"
    - if: "any(keyword in query.lower() for keyword in keywords.reasoning)"  
      then: "models.production.reasoning if paid else models.free.general"
    - if: "any(keyword in query.lower() for keyword in keywords.multimodal)"
      then: "models.production.multimodal"
    - default: "models.production.reasoning if paid else models.free.general"

# API endpoints
endpoints:
  openai: "https://api.openai.com/v1"
  anthropic: "https://api.anthropic.com/v1"
  openrouter: "https://openrouter.ai/api/v1"
  glm: "https://open.bigmodel.cn/api/paas/v4"

# Cost limits (USD per day)
limits:
  daily_cost: 10.0
  per_user_daily: 1.0
  emergency_stop: 50.0