# PolyAgent 配置文件

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30
  write_timeout: 30
  max_body_size: 33554432  # 32MB

database:
  host: "localhost"
  port: 5432
  user: "user"
  password: "pass"
  database: "polyagent"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 10
  max_lifetime: 300  # seconds

redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  max_retries: 3
  pool_size: 10
  min_idle_conn: 2

python_ai:
  base_url: "http://localhost:8000"
  timeout: 60
  max_concurrency: 10
  retry_attempts: 3

auth:
  jwt_secret: "your-super-secret-jwt-key-change-in-production"
  token_expiry: 3600     # 1 hour
  refresh_expiry: 86400  # 24 hours

log:
  level: "info"          # debug, info, warn, error
  format: "json"         # json, text
  output: "stdout"       # stdout, file
  max_size: 100          # MB
  max_backups: 10
  max_age: 30           # days